// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFLaFVSz3maXK8uu94lzDn-rf1eaiu6ho',
    appId: '1:1062010301102:web:c061c7c37ab6caf8ac5b3f',
    messagingSenderId: '1062010301102',
    projectId: 'depresion-e079b',
    authDomain: 'depresion-e079b.firebaseapp.com',
    databaseURL: 'https://depresion-e079b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'depresion-e079b.firebasestorage.app',
    measurementId: 'G-0W97JF8DC9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdXQaZZEROLBoBkDRfUMgwFGIdLmD0v9I',
    appId: '1:1062010301102:android:962dc32c658687eaac5b3f',
    messagingSenderId: '1062010301102',
    projectId: 'depresion-e079b',
    databaseURL: 'https://depresion-e079b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'depresion-e079b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxc35W7HQH0-i1-YAEWphtkp5ff_lx_Qw',
    appId: '1:1062010301102:ios:9a659fb25c9ffd85ac5b3f',
    messagingSenderId: '1062010301102',
    projectId: 'depresion-e079b',
    databaseURL: 'https://depresion-e079b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'depresion-e079b.firebasestorage.app',
    iosBundleId: 'com.example.flutterProjects',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxc35W7HQH0-i1-YAEWphtkp5ff_lx_Qw',
    appId: '1:1062010301102:ios:9a659fb25c9ffd85ac5b3f',
    messagingSenderId: '1062010301102',
    projectId: 'depresion-e079b',
    databaseURL: 'https://depresion-e079b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'depresion-e079b.firebasestorage.app',
    iosBundleId: 'com.example.flutterProjects',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCFLaFVSz3maXK8uu94lzDn-rf1eaiu6ho',
    appId: '1:1062010301102:web:83679fb16edae607ac5b3f',
    messagingSenderId: '1062010301102',
    projectId: 'depresion-e079b',
    authDomain: 'depresion-e079b.firebaseapp.com',
    databaseURL: 'https://depresion-e079b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'depresion-e079b.firebasestorage.app',
    measurementId: 'G-WJY9ZSVT72',
  );
}
